@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteByIndexCommandParser" as DeleteByIndexCommandParser LOGIC_COLOR
participant "d:DeleteByIndexCommand" as DeleteByIndexCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete 1")
activate AddressBookParser

create DeleteByIndexCommandParser
AddressBookParser -> DeleteByIndexCommandParser
activate DeleteByIndexCommandParser

DeleteByIndexCommandParser --> AddressBookParser
deactivate DeleteByIndexCommandParser

AddressBookParser -> DeleteByIndexCommandParser : parse("1")
activate DeleteByIndexCommandParser

create DeleteByIndexCommand
DeleteByIndexCommandParser -> DeleteByIndexCommand
activate DeleteByIndexCommand

DeleteByIndexCommand --> DeleteByIndexCommandParser : d
deactivate DeleteByIndexCommand

DeleteByIndexCommandParser --> AddressBookParser : d
deactivate DeleteByIndexCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteByIndexCommandParser -[hidden]-> AddressBookParser
destroy DeleteByIndexCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteByIndexCommand : execute()
activate DeleteByIndexCommand

DeleteByIndexCommand -> Model : deletePerson(1)
activate Model

Model --> DeleteByIndexCommand
deactivate Model

create CommandResult
DeleteByIndexCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteByIndexCommand
deactivate CommandResult

DeleteByIndexCommand --> LogicManager : result
deactivate DeleteByIndexCommand

[<--LogicManager
deactivate LogicManager
@enduml
